template: Hello, %s!

defaultName: amit sah

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver
  
  # the username
  user: root
  
  # the password
  password: 1234
  
  # the JDBC URL
  url: jdbc:mysql://localhost:3306/user_db
  
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

logging:
  level: INFO
  loggers:
    com.amit: DEBUG
    
    "org.hibernate.SQL":
      level: DEBUG
      # This line stops org.hibernate.SQL (or anything under it) from using the root logger
      additive: false
      appenders:
        - type: file
          currentLogFilename: ./logs/hello-sql.log
          archivedLogFilenamePattern: ./logs/hello-sql-%d.log.gz
          archivedFileCount: 10
          timeZone: IST
